### ISSUE TITLE
Theme preview file missing

### ISSUE THREAD

**Issue by allamiro** [BGSU-LITS/omeka-theme-bgsu#1]
Theme screen preview  in jpg or png format is not available

**Comment by kloor** [comment]
Thanks for the report. This theme is customized for BGSU's Digital Gallery: https://digitalgallery.bgsu.edu/

We didn't write the theme with the intention that other Omeka installations would use it, but we do try to provide all of our projects as open-source. Because of that, we intentionally do not include a preview.

**Comment by allamiro** [comment]
ooh thanks for the reply the theme looks great
